PRINT_ERROR_ERRORS = {
    "03004000": "Z axis homing failed; the task has been stopped.",
    "03004001": "The printer timed out waiting for the nozzle to cool down before homing.",
    "03004002": "Auto Bed Leveling failed; the task has been stopped.",
    "03004005": "The hotend cooling fan speed is abnormal.",
    "03004006": "The nozzle is clogged.",
    "03004008": "The AMS failed to change filament.",
    "03004009": "Homing XY axis failed.",
    "0300400A": "Mechanical resonance frequency identification failed.",
    "0300400B": "Internal communication exception",
    "0300400C": "The task was canceled.",
    "0300400D": "Resume failed after power loss.",
    "0300400E": "The motor self-check failed.",
    "0300400F": "The power supply voltage does not match the printer.",
    "03004010": "Nozzle offset calibration failed.",
    "03004011": "Flow Dynamics Calibration failed; please reinitiate printing or calibration.",
    "03004013": "Printing cannot be initiated while AMS is drying.",
    "03004020": "The nozzle presence detection failed. Please check the Assistant for details.",
    "03004042": "The Laser Safety Window is not properly installed. The task has been stopped.",
    "0300404D": "The current temperature of the hotend, heatbed, or chamber is too high. Please wait for it to cool down to room temperature before restarting the task.",
    "03004052": "Blade Z-axis homing failed",
    "03004066": "Calibration of motion precision failed.",
    "03004067": "Calibration result is over the threshold.",
    "03004068": "Step loss occurred during the motion accuracy enhancement process. Please try again.",
    "03008000": "Printing was paused for unknown reason. You can select 'Resume' to resume the print job.",
    "03008001": "Printing paused due to the pause command added to the printing file.",
    "03008003": "Spaghetti defects were detected by the AI Print Monitoring. Please check the quality of the printed model before continuing your print.",
    "03008007": "There was an unfinished print job when the printer lost power. If the model is still adhered to the build plate, you can try resuming the print job.",
    "03008008": "Nozzle temperature malfunction",
    "03008009": "Heatbed temperature malfunction",
    "0300800A": "A Filament pile-up was detected by AI Print Monitoring. Please clean filament from the waste chute.",
    "0300800B": "The cutter is stuck. Please make sure the cutter handle is out and check the filament sensor cable connection.",
    "0300800C": "Skipped step detected: auto-recover complete; please resume print and check if there are any layer shift problems.",
    "0300800D": "Detected that the extruder is not extruding normally. If the defects are acceptable, select 'Resume' to resume the print job.",
    "0300800E": "The print file is not available. Please check to see if the storage media has been removed.",
    "0300800F": "The door seems to be open, so printing was paused.",
    "03008010": "The hotend cooling fan speed is abnormal.",
    "03008013": "Printing was paused by the user. You can select 'Resume' to continue printing.",
    "03008014": "The nozzle is covered with filament, or the build plate is installed incorrectly. Please cancel this print and clean the nozzle or adjust the build plate according to the actual status. You can also select 'Resume' to resume the print job.",
    "03008016": "The nozzle is clogged with filament. Please cancel this print and clean the nozzle or select 'Resume' to resume the print job.",
    "03008017": "Foreign objects detected on heatbed. Please check and clean the heatbed. Then, select 'Resume' to resume the print job.",
    "03008018": "Chamber temperature malfunction.",
    "03008019": "No build plate is placed.",
    "0300801A": "Filament extrusion error; please check the assistant for troubleshooting. After resolving the issue, decide whether to cancel or resume the print job based on the actual print status.",
    "0300801C": "The extrusion resistance is abnormal. The extruder may be clogged, please refer to the assistant, after trouble shooting, you can select 'Resume' to resume the print job.",
    "0300801D": "The extruder servo motor position sensor is malfunctioning. Please power off the printer first and check if the connection cable is loose.",
    "0300801E": "The extrusion motor is overloaded, please check if the extruder is clogged or the filament is stuck in the tool head.",
    "03008021": "The nozzle may not be installed or not properly installed. Please ensure the nozzle is correctly installed before proceeding.",
    "03008041": "Platform detection timeout: please restart the printer.",
    "03008042": "Task paused because the door or top cover is open.",
    "03008043": "The laser module is abnormal.",
    "03008044": "Fire was detected inside the chamber.",
    "03008045": "Material detection timeout: please restart the printer.",
    "03008046": "Foreign object detect timeout: please restart the printer.",
    "03008047": "Quick-release lever detection time out: please restart the printer.",
    "03008048": "Laser Module unlock has timed out, and the task cannot proceed. Please restart the printer and try again.",
    "03008049": "The current plate is invalid.",
    "0300804A": "Emergency stop button improperly installed. Please reinstall according to the Wiki before proceeding.",
    "0300804B": "Task paused. The Laser Safety Window is open.",
    "0300804E": "This is a printing task. Please detach the Laser/Cutting Module from the Toolhead.",
    "0300804F": "The loading/unloading process is currently ongoing. Please stop the process or remove the laser/cutting module.",
    "03008051": "The cutting module has dropped or the cutting module cable is disconnected; please check the module.",
    "03008054": "Please place the paper required for Print Then Cut.",
    "03008055": "The module mounted on the toolhead does not match the task. Please install the correct module.",
    "03008061": "The mode of Airflow System failed to activate; check the air door condition.",
    "03008062": "The chamber temperature is too high. It may be due to high environmental temperature.",
    "03008063": "The chamber temperature is too high. Please open the top cover and front door to cool down.",
    "03008064": "The chamber temperature is too high. Please open the top cover and front door to cool down. (Open door detection for this print job will be set to 'Notification' level)",
    "03008065": "The temperature of the MC module is too high. Please check the Wiki for possible explanations.",
    "05004001": "Failed to connect to Bambu Cloud. Please check your network connection.",
    "05004002": "Unsupported print file path or name. Please resend the print job.",
    "05004003": "Printing stopped because the printer was unable to parse the file. Please resend your print job.",
    "05004004": "Device is busy and cannot start new task. Please wait for current task to complete before sending new task.",
    "05004005": "Print jobs are not allowed to be sent while updating firmware.",
    "05004006": "There is not enough free storage space for the print job. Restoring to factory settings can free up available space.",
    "05004007": "Print jobs are not allowed to be sent while force updating or when repair updating is required.",
    "05004008": "Starting printing failed; please power cycle the printer and resend the print job.",
    "05004009": "Print jobs are not allowed to be sent while updating logs.",
    "0500400A": "The file name is not supported. Please rename and restart the print job.",
    "0500400B": "There was a problem downloading a file. Please check your network connection and resend the print job.",
    "0500400D": "Please run a self-test and restart the print job.",
    "0500400E": "Printing was cancelled.",
    "05004014": "Slicing for the print job failed. Please check your settings and restart the print job.",
    "05004017": "Binding failed. Please retry or restart the printer and retry.",
    "05004018": "Binding configuration information parsing failed; please try again.",
    "05004019": "The printer has already been bound. Please unbind it and try again.",
    "0500401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before trying again.",
    "0500401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0500401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0500401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0500401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0500401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "05004020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05004022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "05004025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05004028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0500402A": "Failed to connect to the router, which may be caused by wireless interference or being too far away from the router. Please try again or move the printer closer to the router and try again.",
    "0500402B": "Router connection failed due to incorrect password. Please check the password and try again.",
    "0500402C": "Failed to obtain IP address, which may be caused by wireless interference resulting in data transmission failure or the DHCP address pool of the router being full. Please move the printer closer to the router and try again. If the issue persists, please check router settings to see whether the IP addresses have been exhausted.",
    "0500402D": "System exception",
    "0500402E": "System does not support the file system currently used by the USB flash drive. Please replace or format the USB flash drive to FAT32.",
    "0500402F": "USB flash drive sector data is damaged; please format it. If it still cannot be recognized, please replace the USB flash drive.",
    "05004031": "An uncertified accessory was detected, and the device cannot continue working. Please use Bambu Lab accessories or upgrade to the latest firmware.",
    "05004033": "Uncertified AMS detected or AMS firmware not upgraded: the device cannot continue working.",
    "05004034": "Laser Module is not certified; the device cannot continue working. Please use Bambu Lab accessories or upgrade to the latest firmware.",
    "05004035": "BirdsEye Camera is not certified; the device cannot continue working. Please use Bambu Lab accessories or upgrade to the latest firmware.",
    "05004037": "Your sliced file is not compatible with current printer model. This file can't be printed on this printer.",
    "05004038": "The nozzle diameter in sliced file is not consistent with the current nozzle setting. This file can't be printed.",
    "05004039": "The current task does not allow the installation of the laser/cutting module, and the task has been halted.",
    "0500403B": "Laser/cutting tasks cannot be initiated on the machine at the moment. Please use the computer software to start the task.",
    "0500403D": "The toolhead module is not set up. Please set it up before initiating the task.",
    "0500403E": "The current tool head does not support initialization.",
    "0500403F": "Failed to download print job; please check your network connection.",
    "05004040": "Due to power limitations, the AMS is not allowed to use the device's power for drying during printing. Should the drying be stopped?",
    "05004041": "Due to power limitations, only one AMS is allowed to use the device's power for drying during printing. Should the drying be stopped?",
    "05004042": "The AMS is currently being used for printing and cannot initiate drying.",
    "05004043": "Due to power limitations, only one AMS is allowed to use the device's power for drying.",
    "05004050": "Error detected on the print board.",
    "05004052": "Error detected on the hot end.",
    "05004054": "Error detected on the mat.",
    "0500405D": "Laser module Serial Number error: unable to calibrate or make project.",
    "05004065": "The task requires a Laser Platform, but the current one is a Cutting Platform. Please replace it, measure the material thickness in the software, and then restart the task.",
    "05004070": "The laser or cutter module is connected, so the device cannot initiate a 3D printing task.",
    "05004075": "No Laser Platform was detected, which may affect thickness measurement accuracy. Please place the laser platform correctly and ensure the rear markers are not blocked, then restart the thickness measurement in the software before initiating the task.",
    "05004076": "Please place the Laser Platform correctly and ensure the rear markers are not blocked, then restart the thickness measurement in the software before initiating the task.",
    "05008013": "The print file is not available. Please check to see if the storage media has been removed.",
    "05008030": "",
    "05008036": "Your sliced file is not consistent with the current printer model. Continue?",
    "05008051": "Detected build plate is not the same as the Gcode file. Please adjust slicer settings or use the correct plate.",
    "05008053": "The left and right nozzle is not matched with slicing file. Please initiate the print after re-slicing, or continue printing after replacing the correct nozzle. Caution: the hotend temperature is high.",
    "05008055": "Laser module is installed, but a Cutting Platform is detected. Please place a Laser Platform and perform laser calibration.",
    "05008056": "Cutting module is installed, but the laser platform is detected. Please place the cutting platform for calibration.",
    "05008058": "Please place the light grip cutting mat correctly and ensure the marker is exposed.",
    "05008059": "Cutting platform base is not correctly aligned. Please ensure that the four corners of the platform are aligned with the heatbed.",
    "0500805A": "Please place the cutting mat on cutting protection base.",
    "0500805B": "The cutting mat type is unknown; please replace it with the correct cutting mat.",
    "0500805C": "The grip cutting mat type does not match; please place a LightGrip cutting mat.",
    "0500805E": "Cutting module Serial Number error: unable to calibrate or make project.",
    "05008060": "The current module on toolhead does not meet requirements. Please replace the module as per the on-screen instructions.",
    "05008061": "No print plate detected. Please make sure it is placed correctly.",
    "05008062": "The print plate type is unknown; please replace it with the correct plate.",
    "05008063": "The platform is not detected during calibration; please make sure the Laser Platform is properly placed.",
    "05008064": "Please place the Laser Platform correctly and ensure the rear markers are not blocked for laser calibration.",
    "05008066": "The task requires a Cutting Platform, but the current one is a Laser Platform. Please replace it with a Cutting Platform (Cutting Protection Base + LightGrip cutting mat).",
    "05008067": "Please place a LightGrip cutting mat on the cutting protection base.",
    "05008068": "Please place the strong grip cutting mat correctly and ensure the marker is exposed.",
    "05008069": "Unable to recognize the left and right hotend. It might be a non-official hotend, or the hotend mark could be dirty. Please manually set the hotend type.",
    "0500806A": "Unable to recognize the left and right hotend. It might be a non-official hotend, or the hotend mark could be dirty. Please set hotend type before next print.",
    "0500806B": "Quick-release Lever is not locked. Please press it down to secure it.",
    "0500806C": "Please place the cutting platform correctly and ensure the marker is exposed.",
    "0500806D": "Material not detected. Please confirm placement and continue.",
    "0500806E": "Foreign objects detected on heatbed; please check and clean up the heatbed.",
    "0500806F": "The grip cutting mat type does not match; please place a StrongGrip cutting mat.",
    "05008071": "No cutting platform was detected. Please confirm that it has been correctly placed.",
    "05008072": "Live View camera is blocked",
    "05008073": "Heatbed limit block is obstructed or contaminated. Please clean and ensure the limit block is visible, otherwise platform position offset detection may be inaccurate.",
    "05008074": "The Laser Platform is offset. Please ensure that the four corners of the platform are aligned with the heatbed, and the marker is not obstructed.",
    "05008077": "The visual marker was not detected. Please ensure the paper is properly placed.",
    "05008078": "Current material does not match the sliced file settings. Please load the correct material and ensure the QR code on the material is not damaged or dirty.",
    "05008079": "Please follow the instruction to place the Laser Test Material(350g paperboard).",
    "0500807A": "The foreign object detection function is not working. You can continue the task or check the assistant for troubleshooting.",
    "0500807B": "Please place the cutting platform (cutting protection base + LightGrip cutting mat).",
    "0500807C": "Please place the cutting platform (cutting protection base + StrongGrip cutting mat).",
    "0500807D": "This task requires a Cutting Platform, but the current one is a Laser Platform. Please replace it with a Cutting Platform (Cutting Protection Base + StrongGrip Cutting Mat).",
    "0500807E": "Please place a StrongGrip cutting mat on the cutting protection base.",
    "05008080": "The left and right hotend is not installed.",
    "05008081": "The left and right hotend is not installed.",
    "05008082": "Please remove the protective film on the Opaque Glossy Acrylic before processing",
    "05008083": "Material is not allowed in Mounting Calibration. Please remove the material from the platform.",
    "05008084": "The Live View Camera is dirty; please clean it and continue.",
    "05008085": "Nozzle camera is obstructed",
    "05008086": "Nozzle camera lens is dirty, which may affect the AI monitoring functionality. Please clean the surface of the nozzle camera lens as soon as possible.",
    "05008087": "BirdsEye camera is obstructed",
    "05008088": "The Birdseye Camera is dirty",
    "05008089": "Task paused due to Presence Check failed. Please check the printer to continue.",
    "0500808A": "The BirdsEye Camera is installed offset. Please refer to the assistant to reinstall it.",
    "0500808B": "The BirdsEye Camera setup failed. Please clear the heated bed, remove all objects and the mat, and ensure the heatbed markers are visible. Meanwhile, clean BirdsEye Camera and Toolhead Camera, and remove any obstructions that may block the cameras.",
    "0500C010": "USB flash drive read-write exception; please reinsert or replace it.",
    "0500C011": "",
    "0500C032": "Laser/Cutting module connected to the toolhead. The drying process has been automatically stopped.",
    "0500C036": "This is a printing task. Please detach the Laser/Cutting Module from the Toolhead.",
    "0500C07F": "Device is busy and cannot perform this operation. To proceed, please pause or stop the current task.",
    "05014017": "Binding failed. Please retry or restart the printer and retry.",
    "05014018": "Binding configuration information parsing failed; please try again.",
    "05014019": "The printer has already been bound. Please unbind it and try again.",
    "0501401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before trying again.",
    "0501401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0501401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0501401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0501401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0501401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "05014020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05014022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05014023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "05014025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05014026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05014028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05014029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014031": "Device discovery binding is in progress, and the QR code cannot be displayed on the screen. You can wait for the binding to finish or abort the device discovery binding process in the APP/Studio and retry scanning the QR code on the screen for binding.",
    "05014032": "QR code binding is in progress, so device discovery binding cannot be performed. You can scan the QR code on the screen for binding or exit the QR code display page on screen and try device discovery binding.",
    "05014033": "Your APP region does not match with your printer; please download the APP in the corresponding region and register your account again.",
    "05014034": "The slicing progress has not been updated for a long time, and the printing task has exited. Please confirm the parameters and reinitiate printing.",
    "05014035": "The device is in the process of binding and cannot respond to new binding requests.",
    "05014038": "The regional settings do not match the printer; please check the printer's regional settings.",
    "05014039": "Device login has expired; please try to bind again.",
    "05024001": "Current filament will be used in this print job. Settings cannot be changed.",
    "05024002": "The printer does not have motion precision enhancement calibration data; the motion precision enhancement cannot be turned on.",
    "05024003": "The printer is currently printing and the motion accuracy enhancement feature cannot be turned on or off.",
    "05024004": "Some features are not supported by the current device. Please check the Studio feature settings or update the firmware to the latest version.",
    "05024005": "The AMS has not been calibrated yet, so printing cannot be initiated.",
    "05024006": "Unknown module detected, please try updating the firmware to the latest version.",
    "05024007": "Failed to start a new task: filament loading/unloading not completed.",
    "05024008": "Failed to start a new task: The nozzle cold pulling was not completed.",
    "05FE8053": "The left nozzle is not matched with slicing file. Please initiate the print after re-slicing, or continue printing after replacing the correct nozzle. Caution: the hotend temperature is high.",
    "05FE8069": "Unable to recognize the left hotend. It might be a non-official hotend, or the hotend mark could be dirty. Please manually set the hotend type.",
    "05FE806A": "Unable to recognize the left hotend. It might be a non-official hotend, or the hotend mark could be dirty. Please set hotend type before next print.",
    "05FE8080": "The left hotend is not installed.",
    "05FE8081": "The left hotend is not installed.",
    "05FF8053": "The right nozzle is not matched with slicing file. Please initiate the print after re-slicing, or continue printing after replacing the correct nozzle. Caution: the hotend temperature is high.",
    "05FF8069": "Unable to recognize the right hotend. It might be a non-official hotend, or the hotend mark could be dirty. Please manually set the hotend type.",
    "05FF806A": "Unable to recognize the right hotend. It might be a non-official hotend, or the hotend mark could be dirty. Please set hotend type before next print.",
    "05FF8080": "The right hotend is not installed.",
    "05FF8081": "The right hotend is not installed.",
    "07004025": "Failed to read the filament information.",
    "07008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07008004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07008005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07008006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07008007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0700800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS A to the extruder is properly connected.",
    "07008010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07008011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07008012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07008013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07008016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07008017": "AMS A is drying. Please stop drying process before loading/unloading material.",
    "07008021": "AMS setup failed; please refer to the assistant.",
    "07008023": "The cooling process after drying has failed in AMS A.",
    "0700C069": "An error occurred during AMS A drying. Please go to Assistant for more details.",
    "0700C06A": "AMS A is reading RFID. Unable to start drying. Please try again later.",
    "0700C06B": "AMS A is changing filament. Unable to start drying. Please try again later.",
    "0700C06C": "AMS A is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0700C06D": "AMS A is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0700C06E": "AMS A motor is performing self-test. Unable to start drying. Please try again later.",
    "07014025": "Failed to read the filament information.",
    "07018003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07018004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07018005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07018006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07018007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0701800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS B to the extruder is properly connected.",
    "07018010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07018011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07018012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07018013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07018016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07018017": "AMS B is drying. Please stop drying process before loading/unloading material.",
    "07018021": "AMS setup failed; please refer to the assistant.",
    "07018023": "The cooling process after drying has failed in AMS B.",
    "0701C069": "An error occurred during AMS B drying. Please go to Assistant for more details.",
    "0701C06A": "AMS B is reading RFID. Unable to start drying. Please try again later.",
    "0701C06B": "AMS B is changing filament. Unable to start drying. Please try again later.",
    "0701C06C": "AMS B is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0701C06D": "AMS B is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0701C06E": "AMS B motor is performing self-test. Unable to start drying. Please try again later.",
    "07024025": "Failed to read the filament information.",
    "07028003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07028004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07028005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07028006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07028007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0702800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS C to the extruder is properly connected.",
    "07028010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07028011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07028012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07028013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07028016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07028017": "AMS C is drying. Please stop drying process before loading/unloading material.",
    "07028021": "AMS setup failed; please refer to the assistant.",
    "07028023": "The cooling process after drying has failed in AMS C.",
    "0702C069": "An error occurred during AMS C drying. Please go to Assistant for more details.",
    "0702C06A": "AMS C is reading RFID. Unable to start drying. Please try again later.",
    "0702C06B": "AMS C is changing filament. Unable to start drying. Please try again later.",
    "0702C06C": "AMS C is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0702C06D": "AMS C is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0702C06E": "AMS C motor is performing self-test. Unable to start drying. Please try again later.",
    "07034025": "Failed to read the filament information.",
    "07038003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07038004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07038005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07038006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07038007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0703800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS D to the extruder is properly connected.",
    "07038010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07038011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07038012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07038013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07038016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07038017": "AMS D is drying. Please stop drying process before loading/unloading material.",
    "07038021": "AMS setup failed; please refer to the assistant.",
    "07038023": "The cooling process after drying has failed in AMS D.",
    "0703C069": "An error occurred during AMS D drying. Please go to Assistant for more details.",
    "0703C06A": "AMS D is reading RFID. Unable to start drying. Please try again later.",
    "0703C06B": "AMS D is changing filament. Unable to start drying. Please try again later.",
    "0703C06C": "AMS D is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0703C06D": "AMS D is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0703C06E": "AMS D motor is performing self-test. Unable to start drying. Please try again later.",
    "07044025": "Failed to read the filament information.",
    "07048003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07048004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07048005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07048006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07048007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0704800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS E to the extruder is properly connected.",
    "07048010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07048011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07048012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07048013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07048016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07048021": "AMS setup failed; please refer to the assistant.",
    "07048023": "The cooling process after drying has failed in AMS E.",
    "07054025": "Failed to read the filament information.",
    "07058003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07058004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07058005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07058006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07058007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0705800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS F to the extruder is properly connected.",
    "07058010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07058011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07058012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07058013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07058016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07058021": "AMS setup failed; please refer to the assistant.",
    "07058023": "The cooling process after drying has failed in AMS F.",
    "07064025": "Failed to read the filament information.",
    "07068003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07068004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07068005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07068006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07068007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0706800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS G to the extruder is properly connected.",
    "07068010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07068011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07068012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07068013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07068016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07068021": "AMS setup failed; please refer to the assistant.",
    "07068023": "The cooling process after drying has failed in AMS G.",
    "07074025": "Failed to read the filament information.",
    "07078003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07078004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07078005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07078006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07078007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "0707800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS H to the extruder is properly connected.",
    "07078010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07078011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07078012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07078013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07078016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07078021": "AMS setup failed; please refer to the assistant.",
    "07078023": "The cooling process after drying has failed in AMS H.",
    "07FE8001": "Failed to cut the filament of the left extruder. Please check the cutter.",
    "07FE8002": "The cutter of the left extruder is stuck. Please pull out the cutter handle.",
    "07FE8003": "Please pull out the filament on the spool holder  of the left extruder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
    "07FE8004": "Failed to pull back the filament from the left extruder. Please check whether the filament is stuck inside the extruder.",
    "07FE8005": "Failed to feed the filament outside the AMS. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "07FE8006": "Please feed filament into the PTFE tube of the left extruder until it can not be pushed any farther.",
    "07FE8007": "Please observe the nozzle of the left extruder. If the filament has been extruded, select 'Continue'; if it is not, please push the filament forward slightly, and then select 'Retry'.",
    "07FE8010": "Check if the left external filament spool or filament is stuck.",
    "07FE8011": "The external filament connected to the left extruder has run out; please load a new filament.",
    "07FE8012": "Failed to get mapping table; please select 'Resume' to retry.",
    "07FE8013": "Timeout purging old filament of the left extruder: Please check if the filament is stuck or the extruder is clogged.",
    "07FE8020": "Extruder change failed; please refer to the assistant.",
    "07FE8021": "AMS setup failed; please refer to the assistant.",
    "07FE8024": "Extruder position calibration failed; please refer to the assistant.",
    "07FE8025": "Cold pulling timed out. Please promptly operate or check whether the filament is broken inside the extruder, and click the Assistant for details.",
    "07FEC003": "Please pull out the filament on the spool holder of the left extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "07FEC006": "Please feed filament into the PTFE tube of the left extruder until it can not be pushed any farther.",
    "07FEC008": "Please pull out the filament on the spool holder of the left extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "07FEC009": "Please feed filament into the PTFE tube of the left extruder until it can not be pushed any farther.",
    "07FEC00A": "Please observe the nozzle of the left extruder. If the filament has been extruded, select 'Continue'; if not, please push the filament forward slightly and then select 'Retry'.",
    "07FEC010": "Insert the filament until it can not be pushed any farther. There might be slight smoke during purging, so please close the front door and top cover after insertion.",
    "07FEC011": "Please manually and slowly pull out the filament from the extruder. Then click “Continue”.",
    "07FEC012": "Press the black PTFE tube coupler and unplug the PTFE tube. After completing the operation, click 'Continue.'",
    "07FF8001": "Failed to cut the filament of the right extruder. Please check the cutter.",
    "07FF8002": "The cutter of the right extruder is stuck. Please pull out the cutter handle.",
    "07FF8003": "Please pull out the filament on the spool holder  of the right extruder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
    "07FF8004": "Failed to pull back the filament from the right extruder. Please check whether the filament is stuck inside the extruder.",
    "07FF8005": "Failed to feed the filament outside the AMS. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "07FF8006": "Please feed filament into the PTFE tube of the right extruder until it can not be pushed any farther.",
    "07FF8007": "Please observe the nozzle of the right extruder. If the filament has been extruded, select 'Continue'; if it is not, please push the filament forward slightly, and then select 'Retry'.",
    "07FF8010": "Check if the right external filament spool or filament is stuck.",
    "07FF8011": "The external filament connected to the right extruder has run out; please load a new filament.",
    "07FF8012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07FF8013": "Timeout purging old filament of the right extruder: Please check if the filament is stuck or the extruder is clogged.",
    "07FF8020": "Extruder change failed; please refer to the assistant.",
    "07FF8021": "AMS setup failed; please refer to the assistant.",
    "07FF8024": "Extruder position calibration failed; please refer to the assistant.",
    "07FF8025": "Cold pulling timed out. Please promptly operate or check whether the filament is broken inside the extruder, and click the Assistant for details.",
    "07FFC003": "Please pull out the filament on the spool holder of the right extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "07FFC006": "Please feed filament into the PTFE tube of the right extruder until it can not be pushed any farther.",
    "07FFC008": "Please pull out the filament on the spool holder of the right extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "07FFC009": "Please feed filament into the PTFE tube of the right extruder until it can not be pushed any farther.",
    "07FFC00A": "Please observe the nozzle of the right extruder. If the filament has been extruded, select 'Continue'; if not, please push the filament forward slightly and then select 'Retry'.",
    "07FFC010": "Insert the filament until it can not be pushed any farther. There might be slight smoke during purging, so please close the front door and top cover after insertion.",
    "07FFC011": "Please manually and slowly pull out the filament from the extruder. Then click “Continue”.",
    "07FFC012": "Press the black PTFE tube coupler and unplug the PTFE tube. After completing the operation, click 'Continue.'",
    "0C004020": "The setup of BirdsEye Camera failed. Please clear all objects and remove the mat. Make sure the marker is not obstructed. Meanwhile, clean both the BirdsEye Camera and Toolhead Camera, and remove any foreign objects blocking their view.",
    "0C004021": "The setup of BirdsEye Camera failed; please reboot the printer.",
    "0C004022": "The setup of BirdsEye Camera failed.  Please check if the laser module is working properly.",
    "0C004024": "The Birdseye Camera is installed offset. Please refer to the assistant to reinstall it.",
    "0C004025": "The Birdseye Camera is dirty. Please clean it and restart the process.",
    "0C004026": "The Live View Camera initialization failed; please reboot the printer.",
    "0C004027": "The Live View Camera calibration failed. Please refer to the assistant for details and recalibrate the camera after processing.",
    "0C004029": "Material not detected. Please confirm placement and continue.",
    "0C00402A": "The visual marker was not detected. Please re-paste the paper in the correct position. Meanwhile, please clean the Toolhead Camera to prevent contamination and remove any objects that may obstruct its view.",
    "0C00402C": "Device data link error. Please reboot the printer.",
    "0C00402D": "The toolhead camera is not working properly; please reboot the device.",
    "0C00403D": "The vision encoder plate was not detected. Please confirm it is correctly positioned on the heatbed.",
    "0C00403E": "The high-precision nozzle offset calibration has failed, possibly due to a damaged pattern or the similarity of the colors of the two selected filaments. Please clear the printed pattern and replace the filaments with higher color contrast before re-calibrating.",
    "0C004041": "Toolhead camera calibration failed. Please ensure the Calibration Marker on the heatbed or Height Calibration Marker on the homing area is clean and undamaged, then re-run the calibration process.",
    "0C008002": "",
    "0C008005": "Purged filament has piled up in the waste chute, which may cause a tool head collision.",
    "0C008009": "Build plate localization marker was not found.",
    "0C00800B": "The heatbed marker was not detected. Please clear all objects and remove the mat. Make sure the marker is not obstructed.",
    "0C008015": "Objects detected on the platform; please clean them up in a timely manner.",
    "0C008016": "The foreign object detection function is not working. You can continue the task or check assistant for solutions.",
    "0C008017": "Foreign objects detected on the platform; please clean them up on time.",
    "0C008018": "The foreign object detection function is not working. You can continue the task or view the assistant for troubleshooting.",
    "0C008033": "Quick-release Lever is not locked. Please push it down to secure.",
    "0C00803F": "AI detected nozzle clumping. Please check the nozzle condition. Refer to assistant for solutions.",
    "0C008040": "AI detected air-printing defect. Please check the hotend extrusion status. Refer to assistant for solutions.",
    "0C00C004": "Possible spaghetti failure was detected.",
    "0C00C006": "Purged filament may have piled up in the waste chute.",
    "1000C001": "High bed temperature may lead to filament clogging in the nozzle. You may open the chamber door.",
    "1000C002": "Printing CF material with stainless steel may cause nozzle damage.",
    "1000C003": "Enabling Timelapse in traditional mode may cause defects; please activate this feature as needed.",
    "10014001": "Timelapse is not supported as Spiral Vase mode is enabled in slicing presets.",
    "10014002": "Timelapse is not supported as the Print sequence is set to 'By object'.",
    "10018003": "The time-lapse mode is set to Traditional in the slicing file. This may cause surface defects. Would you like to enable it?",
    "10018004": "Prime Tower is not enabled and time-lapse mode is set to Smooth in slicing file. This may cause surface defects. Would you like to enable it?",
    "18004025": "Failed to read the filament information.",
    "18008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18008004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18008005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18008006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18008007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1800800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT A to the extruder is properly connected.",
    "18008010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18008011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18008012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18008013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18008016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18008017": "AMS-HT A is drying. Please stop drying process before loading/unloading material.",
    "18008021": "AMS setup failed; please refer to the assistant.",
    "18008023": "The cooling process after drying has failed in AMS-HT A.",
    "1800C069": "An error occurred during AMS-HT A drying. Please go to Assistant for more details.",
    "1800C06A": "AMS-HT A is reading RFID. Unable to start drying. Please try again later.",
    "1800C06B": "AMS-HT A is changing filament. Unable to start drying. Please try again later.",
    "1800C06C": "AMS-HT A is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1800C06D": "AMS-HT A is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1800C06E": "AMS-HT A motor is performing self-test. Unable to start drying. Please try again later.",
    "18014025": "Failed to read the filament information.",
    "18018003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18018004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18018005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18018006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18018007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1801800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT B to the extruder is properly connected.",
    "18018010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18018011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18018012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18018013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18018016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18018017": "AMS-HT B is drying. Please stop drying process before loading/unloading material.",
    "18018021": "AMS setup failed; please refer to the assistant.",
    "18018023": "The cooling process after drying has failed in AMS-HT B.",
    "1801C069": "An error occurred during AMS-HT B drying. Please go to Assistant for more details.",
    "1801C06A": "AMS-HT B is reading RFID. Unable to start drying. Please try again later.",
    "1801C06B": "AMS-HT B is changing filament. Unable to start drying. Please try again later.",
    "1801C06C": "AMS-HT B is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1801C06D": "AMS-HT B is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1801C06E": "AMS-HT B motor is performing self-test. Unable to start drying. Please try again later.",
    "18024025": "Failed to read the filament information.",
    "18028003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18028004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18028005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18028006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18028007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1802800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT C to the extruder is properly connected.",
    "18028010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18028011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18028012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18028013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18028016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18028017": "AMS-HT C is drying. Please stop drying process before loading/unloading material.",
    "18028021": "AMS setup failed; please refer to the assistant.",
    "18028023": "The cooling process after drying has failed in AMS-HT C.",
    "1802C069": "An error occurred during AMS-HT C drying. Please go to Assistant for more details.",
    "1802C06A": "AMS-HT C is reading RFID. Unable to start drying. Please try again later.",
    "1802C06B": "AMS-HT C is changing filament. Unable to start drying. Please try again later.",
    "1802C06C": "AMS-HT C is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1802C06D": "AMS-HT C is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1802C06E": "AMS-HT C motor is performing self-test. Unable to start drying. Please try again later.",
    "18034025": "Failed to read the filament information.",
    "18038003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18038004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18038005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18038006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18038007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1803800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT D to the extruder is properly connected.",
    "18038010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18038011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18038012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18038013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18038016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18038017": "AMS-HT D is drying. Please stop drying process before loading/unloading material.",
    "18038021": "AMS setup failed; please refer to the assistant.",
    "18038023": "The cooling process after drying has failed in AMS-HT D.",
    "1803C069": "An error occurred during AMS-HT D drying. Please go to Assistant for more details.",
    "1803C06A": "AMS-HT D is reading RFID. Unable to start drying. Please try again later.",
    "1803C06B": "AMS-HT D is changing filament. Unable to start drying. Please try again later.",
    "1803C06C": "AMS-HT D is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1803C06D": "AMS-HT D is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1803C06E": "AMS-HT D motor is performing self-test. Unable to start drying. Please try again later.",
    "18044025": "Failed to read the filament information.",
    "18048003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18048004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18048005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18048006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18048007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1804800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT E to the extruder is properly connected.",
    "18048010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18048011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18048012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18048013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18048016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18048021": "AMS setup failed; please refer to the assistant.",
    "18048023": "The cooling process after drying has failed in AMS-HT E.",
    "1804C069": "An error occurred during AMS-HT E drying. Please go to Assistant for more details.",
    "1804C06A": "AMS-HT E is reading RFID. Unable to start drying. Please try again later.",
    "1804C06B": "AMS-HT E is changing filament. Unable to start drying. Please try again later.",
    "1804C06C": "AMS-HT E is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1804C06D": "AMS-HT E is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1804C06E": "AMS-HT E motor is performing self-test. Unable to start drying. Please try again later.",
    "18054025": "Failed to read the filament information.",
    "18058003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18058004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18058005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18058006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18058007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1805800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT F to the extruder is properly connected.",
    "18058010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18058011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18058012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18058013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18058016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18058021": "AMS setup failed; please refer to the assistant.",
    "18058023": "The cooling process after drying has failed in AMS-HT F.",
    "1805C069": "An error occurred during AMS-HT F drying. Please go to Assistant for more details.",
    "1805C06A": "AMS-HT F is reading RFID. Unable to start drying. Please try again later.",
    "1805C06B": "AMS-HT F is changing filament. Unable to start drying. Please try again later.",
    "1805C06C": "AMS-HT F is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1805C06D": "AMS-HT F is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1805C06E": "AMS-HT F motor is performing self-test. Unable to start drying. Please try again later.",
    "18064025": "Failed to read the filament information.",
    "18068003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18068004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18068005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18068006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18068007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1806800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT G to the extruder is properly connected.",
    "18068010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18068011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18068012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18068013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18068016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18068021": "AMS setup failed; please refer to the assistant.",
    "18068023": "The cooling process after drying has failed in AMS-HT G.",
    "1806C069": "An error occurred during AMS-HT G drying. Please go to Assistant for more details.",
    "1806C06A": "AMS-HT G is reading RFID. Unable to start drying. Please try again later.",
    "1806C06B": "AMS-HT G is changing filament. Unable to start drying. Please try again later.",
    "1806C06C": "AMS-HT G is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1806C06D": "AMS-HT G is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1806C06E": "AMS-HT G motor is performing self-test. Unable to start drying. Please try again later.",
    "18074025": "Failed to read the filament information.",
    "18078003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18078004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18078005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18078006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18078007": "Failed to extrude the filament. Please check if the extruder clogged.",
    "1807800A": "PTFE tube disconnection detected. Please check if the PTFE tube from AMS-HT H to the extruder is properly connected.",
    "18078010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18078011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18078012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18078013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18078016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18078021": "AMS setup failed; please refer to the assistant.",
    "18078023": "The cooling process after drying has failed in AMS-HT H.",
    "1807C069": "An error occurred during AMS-HT H drying. Please go to Assistant for more details.",
    "1807C06A": "AMS-HT H is reading RFID. Unable to start drying. Please try again later.",
    "1807C06B": "AMS-HT H is changing filament. Unable to start drying. Please try again later.",
    "1807C06C": "AMS-HT H is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1807C06D": "AMS-HT H is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1807C06E": "AMS-HT H motor is performing self-test. Unable to start drying. Please try again later.",
    "18FE8001": "Failed to cut the filament of the left extruder. Please check the cutter.",
    "18FE8002": "The cutter of the left extruder is stuck. Please pull out the cutter handle.",
    "18FE8003": "Please pull out the filament on the spool holder  of the left extruder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
    "18FE8004": "Failed to pull back the filament from the left extruder. Please check whether the filament is stuck inside the extruder.",
    "18FE8005": "Failed to feed the filament outside the AMS-HT. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "18FE8006": "Please feed filament into the PTFE tube of the left extruder until it can not be pushed any farther.",
    "18FE8007": "Please observe the nozzle of the left extruder. If the filament has been extruded, select 'Continue'; if it is not, please push the filament forward slightly, and then select 'Retry'.",
    "18FE8011": "The external filament connected to the left extruder has run out; please load a new filament.",
    "18FE8012": "Failed to get mapping table; please select 'Resume' to retry.",
    "18FE8013": "Timeout purging old filament of the left extruder: Please check if the filament is stuck or the extruder is clogged.",
    "18FE8020": "Extruder change failed; please refer to the assistant.",
    "18FE8021": "AMS setup failed; please refer to the assistant.",
    "18FE8024": "Extruder position calibration failed; please refer to the assistant.",
    "18FEC003": "Please pull out the filament on the spool holder of the left extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "18FEC006": "Please feed filament into the PTFE tube of the left extruder until it can not be pushed any farther.",
    "18FEC008": "Please pull out the filament on the spool holder of the left extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "18FEC009": "Please feed filament into the PTFE tube of the left extruder until it can not be pushed any farther.",
    "18FEC00A": "Please observe the nozzle of the left extruder. If the filament has been extruded, select 'Continue'; if not, please push the filament forward slightly and then select 'Retry'.",
    "18FF8001": "Failed to cut the filament of the right extruder. Please check the cutter.",
    "18FF8002": "The cutter of the right extruder is stuck. Please pull out the cutter handle.",
    "18FF8003": "Please pull out the filament on the spool holder  of the right extruder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
    "18FF8004": "Failed to pull back the filament from the right extruder. Please check whether the filament is stuck inside the extruder.",
    "18FF8005": "Failed to feed the filament outside the AMS-HT. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "18FF8006": "Please feed filament into the PTFE tube of the right extruder until it can not be pushed any farther.",
    "18FF8007": "Please observe the nozzle of the right extruder. If the filament has been extruded, select 'Continue'; if it is not, please push the filament forward slightly, and then select 'Retry'.",
    "18FF8011": "The external filament connected to the right extruder has run out; please load a new filament.",
    "18FF8012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18FF8013": "Timeout purging old filament of the right extruder: Please check if the filament is stuck or the extruder is clogged.",
    "18FF8020": "Extruder change failed; please refer to the assistant.",
    "18FF8021": "AMS setup failed; please refer to the assistant.",
    "18FF8024": "Extruder position calibration failed; please refer to the assistant.",
    "18FFC003": "Please pull out the filament on the spool holder of the right extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "18FFC006": "Please feed filament into the PTFE tube of the right extruder until it can not be pushed any farther.",
    "18FFC008": "Please pull out the filament on the spool holder of the right extruder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "18FFC009": "Please feed filament into the PTFE tube of the right extruder until it can not be pushed any farther.",
    "18FFC00A": "Please observe the nozzle of the right extruder. If the filament has been extruded, select 'Continue'; if not, please push the filament forward slightly and then select 'Retry'.",
}
