PRINT_ERROR_ERRORS = {
    "03004000": "Z axis homing failed; the task has been stopped.",
    "03004001": "The printer timed out waiting for the nozzle to cool down before homing.",
    "03004002": "Auto Bed Leveling failed; the task has been stopped.",
    "03004005": "The hotend cooling fan speed is abnormal.",
    "03004006": "The nozzle is clogged.",
    "03004008": "The AMS failed to change filament.",
    "03004009": "Homing XY axis failed.",
    "0300400A": "Mechanical resonance frequency identification failed.",
    "0300400B": "Internal communication exception",
    "0300400C": "The task was canceled.",
    "0300400D": "Resume failed after power loss.",
    "0300400E": "The motor self-check failed.",
    "03004013": "Printing cannot be initiated while AMS is drying.",
    "03004014": "Homing Z axis failed: temperature control abnormality.",
    "03004020": "The nozzle presence detection failed. Please check the Assistant for details.",
    "03004066": "Calibration of motion precision failed.",
    "03004067": "Calibration result is over the threshold.",
    "03008000": "Printing was paused for unknown reason. You can select 'Resume' to resume the print job.",
    "03008001": "Printing paused due to the pause command added to the printing file.",
    "03008002": "First layer defects were detected by the Micro Lidar. Please check the quality of the printed model before continuing your print.",
    "03008003": "Spaghetti defects were detected by the AI Print Monitoring. Please check the quality of the printed model before continuing your print.",
    "03008004": "Filament ran out. Please load new filament.",
    "03008005": "Toolhead front cover fell off. Please remount the front cover and check to make sure your print is going okay.",
    "03008006": "The build plate marker was not detected. Please confirm the build plate is correctly positioned on the heatbed with all four corners aligned, and the marker is visible.",
    "03008007": "There was an unfinished print job when the printer lost power. If the model is still adhered to the build plate, you can try resuming the print job.",
    "03008008": "Nozzle temperature malfunction",
    "03008009": "Heatbed temperature malfunction",
    "0300800A": "A Filament pile-up was detected by AI Print Monitoring. Please clean filament from the waste chute.",
    "0300800B": "The cutter is stuck. Please make sure the cutter handle is out and check the filament sensor cable connection.",
    "0300800C": "Skipped step detected: auto-recover complete; please resume print and check if there are any layer shift problems.",
    "0300800D": "Detected that the extruder is not extruding normally. If the defects are acceptable, select 'Resume' to resume the print job.",
    "0300800E": "The print file is not available. Please check to see if the storage media has been removed.",
    "0300800F": "The door seems to be open, so printing was paused.",
    "03008010": "The hotend cooling fan speed is abnormal.",
    "03008011": "Detected build plate is not the same as the Gcode file. Please adjust slicer settings or use the correct plate.",
    "03008013": "Printing was paused by the user. You can select 'Resume' to continue printing.",
    "03008014": "The nozzle is covered with filament, or the build plate is installed incorrectly. Please cancel this print and clean the nozzle or adjust the build plate according to the actual status. You can also select 'Resume' to resume the print job.",
    "03008016": "The nozzle is clogged with filament. Please cancel this print and clean the nozzle or select 'Resume' to resume the print job.",
    "03008017": "Foreign objects detected on heatbed. Please check and clean the heatbed. Then, select 'Resume' to resume the print job.",
    "03008018": "Chamber temperature malfunction.",
    "03008019": "No build plate is placed.",
    "05004001": "Failed to connect to Bambu Cloud. Please check your network connection.",
    "05004002": "Unsupported print file path or name. Please resend the print job.",
    "05004003": "Printing stopped because the printer was unable to parse the file. Please resend your print job.",
    "05004004": "Device is busy and cannot start new task. Please wait for current task to complete before sending new task.",
    "05004005": "Print jobs are not allowed to be sent while updating firmware.",
    "05004006": "There is not enough free storage space for the print job. Restoring to factory settings can free up available space.",
    "05004007": "The device requires a repair upgrade, and printing is currently unavailable.",
    "05004008": "Starting printing failed; please power cycle the printer and resend the print job.",
    "05004009": "Print jobs are not allowed to be sent while updating logs.",
    "0500400A": "The file name is not supported. Please rename and restart the print job.",
    "0500400B": "There was a problem downloading a file. Please check your network connection and resend the print job.",
    "0500400C": "Please insert a MicroSD card and restart the print job.",
    "0500400D": "Please run a self-test and restart the print job.",
    "0500400E": "Printing was cancelled.",
    "05004014": "Slicing for the print job failed. Please check your settings and restart the print job.",
    "05004015": "There is not enough free storage space for the print job. Please format or clear files from the MicroSD card to free up space.",
    "05004016": "The MicroSD Card is write-protected. Please replace the MicroSD Card.",
    "05004017": "Binding failed. Please retry or restart the printer and retry.",
    "05004018": "Binding configuration information parsing failed; please try again.",
    "05004019": "The printer has already been bound. Please unbind it and try again.",
    "0500401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before trying again.",
    "0500401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0500401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0500401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0500401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0500401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "05004020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05004022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "05004025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05004028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0500402A": "Failed to connect to the router, which may be caused by wireless interference or being too far away from the router. Please try again or move the printer closer to the router and try again.",
    "0500402B": "Router connection failed due to incorrect password. Please check the password and try again.",
    "0500402C": "Failed to obtain IP address, which may be caused by wireless interference resulting in data transmission failure or the DHCP address pool of the router being full. Please move the printer closer to the router and try again. If the issue persists, please check router settings to see whether the IP addresses have been exhausted.",
    "0500402D": "System exception",
    "0500402E": "The system does not support the file system currently used by the MicroSD card. Please replace the MicroSD card or format it to FAT32.",
    "0500402F": "The MicroSD card sector data is damaged. Please use the SD card repair tool to repair or format it. If it still cannot be identified, please replace the MicroSD card.",
    "05004031": "The accessory firmware does not match the printer. Please update it on the 'Firmware' page.",
    "05004033": "The AMS firmware does not match the printer. Please update it on the 'Firmware' page.",
    "05004037": "Your sliced file is not compatible with current printer model. This file can't be printed on this printer.",
    "05004038": "The nozzle diameter in sliced file is not consistent with the current nozzle setting. This file can't be printed.",
    "0500403C": "The nozzle setup does not match the slicing file. Please initiate the print after re-slicing.",
    "05004040": "The printer has reached its power limit. Please connect a dedicated power adapter to this AMS to enable drying.",
    "05004041": "The AMS drying cannot be started during printing.",
    "05004042": "Due to power limitations, starting AMS drying will pause current operations such as nozzle heating and fan running. Do you want to proceed with drying?",
    "05004043": "Due to power limitations, only one AMS is allowed to use the device's power for drying.",
    "05004098": "Uncertified AMS A detected; the device cannot continue working. Please reconnect the AMS cable or restart the printer.",
    "0500409D": "The firmware of AMS A does not match the printer; the device cannot continue working. Please upgrade it on the 'Firmware' page.",
    "05008013": "The print file is not available. Please check to see if the storage media has been removed.",
    "05008030": "",
    "05008036": "Your sliced file is not consistent with the current printer model. Continue?",
    "0500C010": "MicroSD Card read/write exception: please reinsert or replace the MicroSD Card.",
    "0500C011": "",
    "05014017": "Binding failed. Please retry or restart the printer and retry.",
    "05014018": "Binding configuration information parsing failed; please try again.",
    "05014019": "The printer has already been bound. Please unbind it and try again.",
    "0501401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before trying again.",
    "0501401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0501401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0501401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0501401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "0501401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "05014020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05014022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05014023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "05014025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05014026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05014028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05014029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05014031": "Device discovery binding is in progress, and the QR code cannot be displayed on the screen. You can wait for the binding to finish or abort the device discovery binding process in the APP/Studio and retry scanning the QR code on the screen for binding.",
    "05014032": "QR code binding is in progress, so device discovery binding cannot be performed. You can scan the QR code on the screen for binding or exit the QR code display page on screen and try device discovery binding.",
    "05014033": "Your APP region does not match with your printer; please download the APP in the corresponding region and register your account again.",
    "05014034": "The slicing progress has not been updated for a long time, and the printing task has exited. Please confirm the parameters and reinitiate printing.",
    "05014035": "The device is in the process of binding and cannot respond to new binding requests.",
    "05014038": "The regional settings do not match the printer; please check the printer's regional settings.",
    "05014039": "Device login has expired; please try to bind again.",
    "05014098": "Uncertified AMS B detected; the device cannot continue working. Please reconnect the AMS cable or restart the printer.",
    "0501409D": "The firmware of AMS B does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05024001": "Current filament will be used in this print job. Settings cannot be changed.",
    "05024004": "Some features are not supported by the current device. Please check the Studio feature settings or update the firmware to the latest version.",
    "05024007": "",
    "05024008": "",
    "05024009": "",
    "0502400A": "",
    "0502400B": "",
    "0502400C": "",
    "0502400D": "Failed to start a new task: filament loading/unloading not completed.",
    "05024098": "Uncertified AMS C detected; the device cannot continue working. Please reconnect the AMS cable or restart the printer.",
    "0502409D": "The firmware of AMS C does not match the printer; the device cannot continue working. Please upgrade it on the 'Firmware' page.",
    "05034098": "Uncertified AMS D detected; the device cannot continue working. Please reconnect the AMS cable or restart the printer.",
    "0503409D": "The firmware of AMS D does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05804096": "Uncertified AMS-HT A detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0580409C": "The firmware of AMS-HT A does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05814096": "Uncertified AMS-HT B detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0581409C": "The firmware of AMS-HT B does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05824096": "Uncertified AMS-HT C detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0582409C": "The firmware of AMS-HT C does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05834096": "Uncertified AMS-HT D detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0583409C": "The firmware of AMS-HT D does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05844096": "Uncertified AMS-HT F detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0584409C": "The firmware of AMS-HT E does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05854096": "Uncertified AMS-HT E detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0585409C": "The firmware of AMS-HT F does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05864096": "Uncertified AMS-HT G detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0586409C": "The firmware of AMS-HT G does not match the printer; the device cannot continue working. Please update it on the 'Firmware' page.",
    "05874096": "Uncertified AMS-HT H detected; the device cannot continue working. Please reconnect the AMS-HT cable or restart the printer.",
    "0587409C": "The firmware of AMS-HT H does not match the printer; the device cannot continue working. Please upgrade it on the 'Firmware' page.",
    "07004001": "The AMS has been disabled for a print, but it still has filament loaded. Please unload the AMS filament and switch to the spool holder filament for printing.",
    "07008001": "Failed to cut the filament. Please check the cutter.",
    "07008002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07008004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07008005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07008006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07008007": "Extruding filament failed. The extruder might be clogged.",
    "07008010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07008011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07008012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07008013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07008016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07008023": "The cooling process after drying has failed in AMS A.",
    "0700C069": "An error occurred during AMS A drying. Please go to Assistant for more details.",
    "0700C06A": "AMS A is reading RFID. Unable to start drying. Please try again later.",
    "0700C06B": "AMS A is changing filament. Unable to start drying. Please try again later.",
    "0700C06C": "AMS A is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0700C06D": "AMS A is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0700C06E": "AMS A motor is performing self-test. Unable to start drying. Please try again later.",
    "07014001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07018001": "Failed to cut the filament. Please check the cutter.",
    "07018002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07018003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07018004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07018005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07018006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07018007": "Extruding filament failed. The extruder might be clogged.",
    "07018010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07018011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07018012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07018013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07018016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07018023": "The cooling process after drying has failed in AMS B.",
    "0701C069": "An error occurred during AMS B drying. Please go to Assistant for more details.",
    "0701C06A": "AMS B is reading RFID. Unable to start drying. Please try again later.",
    "0701C06B": "AMS B is changing filament. Unable to start drying. Please try again later.",
    "0701C06C": "AMS B is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0701C06D": "AMS B is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0701C06E": "AMS B motor is performing self-test. Unable to start drying. Please try again later.",
    "07024001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07028001": "Failed to cut the filament. Please check the cutter.",
    "07028002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07028003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07028004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07028005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07028006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07028007": "Extruding filament failed. The extruder might be clogged.",
    "07028010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07028011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07028012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07028013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07028016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07028023": "The cooling process after drying has failed in AMS C.",
    "0702C069": "An error occurred during AMS C drying. Please go to Assistant for more details.",
    "0702C06A": "AMS C is reading RFID. Unable to start drying. Please try again later.",
    "0702C06B": "AMS C is changing filament. Unable to start drying. Please try again later.",
    "0702C06C": "AMS C is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0702C06D": "AMS C is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0702C06E": "AMS C motor is performing self-test. Unable to start drying. Please try again later.",
    "07034001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07038001": "Failed to cut the filament. Please check the cutter.",
    "07038002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07038003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07038004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07038005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07038006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07038007": "Extruding filament failed. The extruder might be clogged.",
    "07038010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07038011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07038012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07038013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07038016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07038023": "The cooling process after drying has failed in AMS D.",
    "0703C069": "An error occurred during AMS D drying. Please go to Assistant for more details.",
    "0703C06A": "AMS D is reading RFID. Unable to start drying. Please try again later.",
    "0703C06B": "AMS D is changing filament. Unable to start drying. Please try again later.",
    "0703C06C": "AMS D is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0703C06D": "AMS D is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0703C06E": "AMS D motor is performing self-test. Unable to start drying. Please try again later.",
    "07048003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07048004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07048005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07048006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07048007": "Extruding filament failed. The extruder might be clogged.",
    "07048010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07048011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07048012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07048016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07048023": "The cooling process after drying has failed in AMS E.",
    "07058003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07058004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07058005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07058006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07058007": "Extruding filament failed. The extruder might be clogged.",
    "07058010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07058011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07058012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07058016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07058023": "The cooling process after drying has failed in AMS F.",
    "07068003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07068004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07068005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07068006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07068007": "Extruding filament failed. The extruder might be clogged.",
    "07068010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07068011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07068012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07068016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07068023": "The cooling process after drying has failed in AMS G.",
    "07078003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07078004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07078005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07078006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07078007": "Extruding filament failed. The extruder might be clogged.",
    "07078010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07078011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07078012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07078016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07078023": "The cooling process after drying has failed in AMS H.",
    "07FF4001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07FF8001": "Failed to cut the filament. Please check the cutter.",
    "07FF8002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07FF8003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
    "07FF8004": "Failed to pull back the filament from the toolhead to AMS. Please check whether the filament or the spool is stuck.",
    "07FF8005": "Failed to feed the filament outside the AMS. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "07FF8006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "07FF8007": "Please observe the nozzle. If the filament has been extruded, select 'Done'; if it is not, please push the filament forward slightly, and then select 'Retry'.",
    "07FF8010": "Check if the external filament spool or filament is stuck.",
    "07FF8011": "External filament has run out; please load a new filament.",
    "07FF8012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "07FF8013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07FFC003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "07FFC006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "07FFC008": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS)",
    "07FFC009": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "07FFC00A": "Please observe the nozzle. If the filament has been extruded, select 'Continue'; if not, please push the filament forward slightly and then select 'Retry'.",
    "0C00402C": "Device data link error. Please reboot the printer.",
    "0C00402D": "The toolhead camera is not working properly; please reboot the device.",
    "0C008001": "First layer defects were detected. If the defects are acceptable, select 'Resume' to resume the print job.",
    "0C008002": "",
    "0C008005": "Purged filament has piled up in the waste chute, which may cause a tool head collision.",
    "0C008009": "Build plate localization marker was not found.",
    "0C00C003": "Possible defects were detected in the first layer.",
    "0C00C004": "Possible spaghetti failure was detected.",
    "0C00C006": "Purged filament may have piled up in the waste chute.",
    "1000C001": "High bed temperature may lead to filament clogging in the nozzle. You may open the chamber door.",
    "1000C002": "Printing CF material with stainless steel may cause nozzle damage.",
    "1000C003": "Enabling Timelapse in traditional mode may cause defects; please activate this feature as needed.",
    "10014001": "Timelapse is not supported as Spiral Vase mode is enabled in slicing presets.",
    "10014002": "Timelapse is not supported as the Print sequence is set to 'By object'.",
    "10018003": "The time-lapse mode is set to Traditional in the slicing file. This may cause surface defects. Would you like to enable it?",
    "10018004": "Prime Tower is not enabled and time-lapse mode is set to Smooth in slicing file. This may cause surface defects. Would you like to enable it?",
    "18008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18008004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18008005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18008006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18008007": "Extruding filament failed. The extruder might be clogged.",
    "18008010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18008011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18008012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18008016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18008023": "The cooling process after drying has failed in AMS-HT A.",
    "1800C069": "An error occurred during AMS-HT A drying. Please go to Assistant for more details.",
    "1800C06A": "AMS-HT A is reading RFID. Unable to start drying. Please try again later.",
    "1800C06B": "AMS-HT A is changing filament. Unable to start drying. Please try again later.",
    "1800C06C": "AMS-HT A is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1800C06D": "AMS-HT A is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1800C06E": "AMS-HT A motor is performing self-test. Unable to start drying. Please try again later.",
    "18018003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18018004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18018005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18018006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18018007": "Extruding filament failed. The extruder might be clogged.",
    "18018010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18018011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18018012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18018016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18018023": "The cooling process after drying has failed in AMS-HT B.",
    "1801C069": "An error occurred during AMS-HT B drying. Please go to Assistant for more details.",
    "1801C06A": "AMS-HT B is reading RFID. Unable to start drying. Please try again later.",
    "1801C06B": "AMS-HT B is changing filament. Unable to start drying. Please try again later.",
    "1801C06C": "AMS-HT B is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1801C06D": "AMS-HT B is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1801C06E": "AMS-HT B motor is performing self-test. Unable to start drying. Please try again later.",
    "18028003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18028004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18028005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18028006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18028007": "Extruding filament failed. The extruder might be clogged.",
    "18028010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18028011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18028012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18028016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18028023": "The cooling process after drying has failed in AMS-HT C.",
    "1802C069": "An error occurred during AMS-HT C drying. Please go to Assistant for more details.",
    "1802C06A": "AMS-HT C is reading RFID. Unable to start drying. Please try again later.",
    "1802C06B": "AMS-HT C is changing filament. Unable to start drying. Please try again later.",
    "1802C06C": "AMS-HT C is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1802C06D": "AMS-HT C is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1802C06E": "AMS-HT C motor is performing self-test. Unable to start drying. Please try again later.",
    "18038003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18038004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18038005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18038006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18038007": "Extruding filament failed. The extruder might be clogged.",
    "18038010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18038011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18038012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18038016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18038023": "The cooling process after drying has failed in AMS-HT D.",
    "1803C069": "An error occurred during AMS-HT D drying. Please go to Assistant for more details.",
    "1803C06A": "AMS-HT D is reading RFID. Unable to start drying. Please try again later.",
    "1803C06B": "AMS-HT D is changing filament. Unable to start drying. Please try again later.",
    "1803C06C": "AMS-HT D is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1803C06D": "AMS-HT D is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1803C06E": "AMS-HT D motor is performing self-test. Unable to start drying. Please try again later.",
    "18048003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18048004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18048005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18048006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18048007": "Extruding filament failed. The extruder might be clogged.",
    "18048010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18048011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18048012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18048016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18048023": "The cooling process after drying has failed in AMS-HT E.",
    "1804C069": "An error occurred during AMS-HT E drying. Please go to Assistant for more details.",
    "1804C06A": "AMS-HT E is reading RFID. Unable to start drying. Please try again later.",
    "1804C06B": "AMS-HT E is changing filament. Unable to start drying. Please try again later.",
    "1804C06C": "AMS-HT E is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1804C06D": "AMS-HT E is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1804C06E": "AMS-HT E motor is performing self-test. Unable to start drying. Please try again later.",
    "18058003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18058004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18058005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18058006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18058007": "Extruding filament failed. The extruder might be clogged.",
    "18058010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18058011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18058012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18058016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18058023": "The cooling process after drying has failed in AMS-HT F.",
    "1805C069": "An error occurred during AMS-HT F drying. Please go to Assistant for more details.",
    "1805C06A": "AMS-HT F is reading RFID. Unable to start drying. Please try again later.",
    "1805C06B": "AMS-HT F is changing filament. Unable to start drying. Please try again later.",
    "1805C06C": "AMS-HT F is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1805C06D": "AMS-HT F is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1805C06E": "AMS-HT F motor is performing self-test. Unable to start drying. Please try again later.",
    "18068003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18068004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18068005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18068006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18068007": "Extruding filament failed. The extruder might be clogged.",
    "18068010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18068011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18068012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18068016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18068023": "The cooling process after drying has failed in AMS-HT G.",
    "1806C069": "An error occurred during AMS-HT G drying. Please go to Assistant for more details.",
    "1806C06A": "AMS-HT G is reading RFID. Unable to start drying. Please try again later.",
    "1806C06B": "AMS-HT G is changing filament. Unable to start drying. Please try again later.",
    "1806C06C": "AMS-HT G is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1806C06D": "AMS-HT G is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1806C06E": "AMS-HT G motor is performing self-test. Unable to start drying. Please try again later.",
    "18078003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18078004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18078005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18078006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18078007": "Extruding filament failed. The extruder might be clogged.",
    "18078010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18078011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "18078012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
    "18078016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18078023": "The cooling process after drying has failed in AMS-HT H.",
    "1807C069": "An error occurred during AMS-HT H drying. Please go to Assistant for more details.",
    "1807C06A": "AMS-HT H is reading RFID. Unable to start drying. Please try again later.",
    "1807C06B": "AMS-HT H is changing filament. Unable to start drying. Please try again later.",
    "1807C06C": "AMS-HT H is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1807C06D": "AMS-HT H is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1807C06E": "AMS-HT H motor is performing self-test. Unable to start drying. Please try again later.",
    "18FF8005": "Failed to feed the filament outside the AMS-HT. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "18FF8012": "Failed to get AMS mapping table; please select 'Resume' to retry.",
}
