PRINT_ERROR_ERRORS = {
    "03004000": "Printing stopped because homing Z axis failed.",
    "03004001": "The printer timed out waiting for the nozzle to cool down before homing.",
    "03004002": "Printing Stopped because Auto Bed Leveling failed.",
    "03004003": "Nozzle temperature malfunction.",
    "03004004": "Heatbed temperature malfunction.",
    "03004005": "The hotend cooling fan speed is abnormal.",
    "03004006": "The nozzle is clogged.",
    "03004008": "The AMS failed to change filament.",
    "03004009": "Homing XY axis failed.",
    "0300400A": "Mechanical resonance frequency identification failed.",
    "0300400B": "Internal communication exception.",
    "0300400C": "Printing was cancelled.",
    "0300400D": "Resume failed after power loss.",
    "0300400E": "The motor self-check failed.",
    "0300400F": "No build plate is placed.",
    "03008000": "Printing was paused for unknown reason. You can tap 'Resume' to resume the print job.",
    "03008001": "Printing paused. It was due to the pause command added in the printing file.",
    "03008002": "First layer defects were detected by the Micro Lidar. Please check the quality of the printed model before continuing your print.",
    "03008003": "Spaghetti defects were detected by the AI Print Monitoring. Please check the quality of the printed model before continuing your print.",
    "03008004": "Filament ran out. Please load new filament.",
    "03008005": "Toolhead front cover fell off. Please remount the front cover and check to make sure your print is going okay.",
    "03008006": "The build plate marker was not detected. Please confirm the build plate is correctly positioned on the heatbed with all four corners aligned, and the maker is clear.",
    "03008007": "There was an unfinished print job when the printer lost power. If the model is still adhered to the build plate, you can try resuming the print job.",
    "03008008": "Printing Stopped because nozzle temperature problem.",
    "03008009": "Heatbed temperature malfunction.",
    "0300800A": "A Filament pile-up was detected by the AI Print Monitoring. Please clean the filament from the waste chute.",
    "0300800B": "The cutter is stuck. Please make sure the cutter handle is out, and check the filament sensor cable connection.",
    "0300800C": "Skipping step detected, auto-recover complete; please resume print and check if there are any layer shift problems.",
    "0300800D": "Some objects have fallen down, or the extruder is not extruding normally. If the defects are acceptable, click 'Resume' button to resume the print job.",
    "0300800E": "The print file is not available. Please check to see if the storage media has been removed.",
    "0300800F": "The door seems to be open, so printing was paused.",
    "03008010": "The hotend cooling fan speed is abnormal.",
    "03008011": "Detected build plate is not the same as the Gcode file. Please adjust slicer settings or use the correct plate.",
    "03008012": "",
    "03008013": "Printing was paused by the user. You can select 'Resume' to continue printing.",
    "03008014": "The nozzle is covered with filaments, or the build plate is installed incorrectly. Please cancel this printing and clean the nozzle or adjust the build plate according to the actual status, or tap 'Resume' button to resume the print job.",
    "03008015": "The filament on external spool has run out, please load new filament. If the filament is loaded, please select 'Resume'.",
    "03008016": "The nozzle is clogged up with filaments. Please cancel this printing and clean the nozzle according to the actual status, or tap 'Resume' button to resume the print job.",
    "03008017": "Foreign objects detected on heatbed, Please check and clean the heatbed, Then tap 'Resume' button to resume the print job.",
    "03008018": "Chamber temperature malfunction.",
    "03008019": "No build plate is placed.",
    "0300801B": "Nozzle temperature problem detected. Refer to the Assistant to re-connect the hotend connector. POWER OFF the printer before this operation to avoid a short circuit.",
    "05004001": "Failed to connect to Bambu Cloud. Please check your network connection.",
    "05004002": "Unsupported print file path or name. Please resend the printing job.",
    "05004003": "Printing stopped because the printer was unable to parse the file. Please resend your print job.",
    "05004004": "The printer can't receive new print jobs while printing. Resend after the current print finishes.",
    "05004005": "Print jobs are not allowed to be sent while updating firmware.",
    "05004006": "There is not enough free storage space for the print job. Restoring to factory settings can release available space.",
    "05004007": "Print jobs are not allowed to be sent while force updating or when repair updating is required.",
    "05004008": "Starting printing failed. please power cycle the printer and resend the print job.",
    "05004009": "Print jobs are not allowed to be sent while updating logs.",
    "0500400A": "The file name is not supported. Please rename and restart the printing job.",
    "0500400B": "There was a problem downloading a file. Please check you network connection and resend the printing job.",
    "0500400C": "Please insert a MicroSD card and restart the printing job.",
    "0500400D": "Please run a self-test and restart the printing job.",
    "0500400E": "Printing was cancelled.",
    "05004012": "The door seems to be open, so printing was paused.",
    "05004014": "Slicing for the print job failed. Please check your settings and restart the print job.",
    "05004015": "There is not enough free storage space for the print job. Please format or clean MicroSD card to release available space.",
    "05004016": "The MicroSD Card is write-protected. Please replace the MicroSD Card.",
    "05004017": "Binding failed. Please retry or restart the printer and retry.",
    "05004018": "Binding configuration information parsing failed,  please try again.",
    "05004019": "The printer has already been bound. Please unbind it and try again.",
    "0500401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration and then try again.",
    "0500401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "0500401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "0500401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0500401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "0500401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "05004020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05004021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05004022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "05004023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05004024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "05004025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "05004026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05004027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05004028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "05004029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "0500402A": "Failed to connect to the router, which may be caused by wireless interference or being too far away from the router. Please try again or move the printer closer to the router and try again.",
    "0500402B": "Router connection failed due to incorrect password. Please check the password and try again.",
    "0500402C": "Failed to obtain IP address, which may be caused by wireless interference resulting in data transmission failure or DHCP address pool of the router being full. Please move the printer closer to the router and try again. If the issue persists, please check router settings to see whether the IP addresses have been exhausted.",
    "0500402D": "System exception.",
    "0500402E": "The system does not support the file system currently used by the Micro SD card. Please replace the Micro SD card or format the current Micro SD card to FAT32.",
    "0500402F": "The Micro SD card sector data is damaged. Please use the SD card repair tool to repair or format it. If it still cannot be identified, please replace the Micro SD card.",
    "05004031": "An uncertified accessory was detected, and the device cannot continue working.",
    "05004033": "Uncertified AMS detected or AMS firmware not upgraded, the device cannot continue working.",
    "05004037": "Your sliced file is not compatible with current printer model. This file can't be printed on this printer.",
    "05004038": "The nozzle diameter in sliced file is not consistent with the current nozzle setting. This file can't be printed.",
    "0500403A": "The current temperature is too low. In order to protect you and your printer. Printing task, moving axis and other operations are disabled. Please move the printer to an environment above 10 celsius degree.",
    "05008013": "The print file is not available. Please check to see if the storage media has been removed.",
    "05008030": "",
    "05008036": "Your sliced file is not consistent with the current printer model. Continue?",
    "0500C010": "MicroSD Card read/write exception. please reinsert or replace MicroSD Card .",
    "0500C011": "",
    "05014017": "Binding failed. Please retry or restart the printer and retry.",
    "05014018": "Binding configuration information parsing failed,  please try again.",
    "05014019": "The printer has already been bound. Please unbind it and try again.",
    "0501401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration and then try again.",
    "0501401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "0501401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "0501401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0501401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "0501401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "05014020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05014021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05014022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "05014023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05014024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "05014025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "05014026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05014027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "05014028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer service.",
    "05014029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer service.",
    "05014031": "Device discovery binding is in progress, and the QR code cannot be displayed on the screen. You can wait for the binding to finish or abort the device discovery binding process in the APP/Studio and retry scanning the QR code on the screen for binding.",
    "05014032": "QR code binding is in progress, so device discovery binding cannot be performed. You can scan the QR code on the screen for binding or exit the QR code display page on screen and try device discovery binding.",
    "05014033": "Your APP region is not matched with your printer; please download the APP in the corresponding region and register your account again.",
    "05014034": "The slicing progress has not been updated for a long time, and the printing task has exited. Please confirm the parameters and reinitiate printing.",
    "05014035": "The device is in the process of binding and cannot respond to new binding requests.",
    "05014038": "The region settings do not match the printer; please check the printer's region settings.",
    "05014039": "Device login has expired, please try to bind again.",
    "05024001": "Current filament will be used in this print job. Settings cannot be changed.",
    "0514039": "Device login has expired; please try to bind again.",
    "07004001": "The AMS has been disabled for a print, but it still has filament loaded. Please unload the AMS filament , and switch to the spool holder filament for printing.",
    "07008001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "07008002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07008004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07008005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07008006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07008007": "Extruding filament failed. The extruder might be clogged.",
    "07008010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07008011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07008012": "Failed to get AMS mapping table; please click 'Retry' to continue.",
    "07008013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged. After troubleshooting, click the 'Retry' button.",
    "07014001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07018001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "07018002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "07018003": "Failed to pull out the filament from the extruder. There may be an extruder clog or broken filament inside the extruder.",
    "07018004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07018005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07018006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool.",
    "07018007": "Failed to extrude the filament. Please check if the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "07018010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07018011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07018012": "Failed to get AMS mapping table; please click 'Retry' to continue.",
    "07018013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged. After troubleshooting, click the 'Retry' button.",
    "07024001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07028001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "07028002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "07028003": "Failed to pull out the filament from the extruder. Please check whether the extruder is clogged or whether the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "07028004": "Failed to pull back the filament from the toolhead to AMS. Please check whether the filament or the spool is stuck. After troubleshooting, click the 'Retry' button.",
    "07028005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07028006": "Failed to feed the filament into the toolhead. Please check whether the filament or the spool is stuck. After troubleshooting, click the 'Retry' button.",
    "07028007": "Failed to extrude the filament. Please check if the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "07028010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07028011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07028012": "Failed to get AMS mapping table; please click 'Retry' to continue.",
    "07028013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged. After troubleshooting, click the 'Retry' button.",
    "07034001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07038001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "07038002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "07038003": "Failed to pull out the filament from the extruder. Please check whether the extruder is clogged or whether the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "07038004": "Failed to pull back the filament from the toolhead to AMS. Please check whether the filament or the spool is stuck. After troubleshooting, click the 'Retry' button.",
    "07038005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07038006": "Failed to feed the filament into the toolhead. Please check whether the filament or the spool is stuck. After troubleshooting, click the 'Retry' button.",
    "07038007": "Failed to extrude the filament. Please check if the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "07038010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07038011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07038012": "Failed to get AMS mapping table; please click 'Retry' to continue.",
    "07038013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged. After troubleshooting, click the 'Retry' button.",
    "07FF4001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07FF8001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "07FF8002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "07FF8003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect PTFE tube if you are about to use AMS)",
    "07FF8004": "Failed to pull back the filament from the toolhead to AMS. Please check whether the filament or the spool is stuck. After troubleshooting, click the 'retry' button.",
    "07FF8005": "Failed to feed the filament outside the AMS. Please clip the end of the filament flat and check to see if the spool is stuck. After troubleshooting, click the 'Retry' button.",
    "07FF8006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "07FF8007": "Please observe the nozzle. If the filament has been extruded, click 'Done'; if it is not, please push the filament forward slightly and then click 'Retry'.",
    "07FF8010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07FF8011": "External filament has run out, please load a new filament.",
    "07FF8012": "Failed to get AMS mapping table; please click 'Retry' to continue.",
    "07FF8013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged. After troubleshooting, click the 'Retry' button.",
    "07FFC003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder or PTFE Tube. (Connect PTFE tube if you are about to use AMS)",
    "07FFC006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "07FFC008": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect PTFE tube if you are about to use AMS)",
    "07FFC009": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "07FFC00A": "Please observe the nozzle. If the filament has been extruded, click 'Done'; if it is not, please push the filament forward slightly and then click 'Retry'.",
    "0C00402A": "",
    "0C008001": "First layer defects were detected. If the defects are acceptable, click 'Resume' button to resume the print job.",
    "0C008002": "Spaghetti failure was detected.",
    "0C008005": "Purged filament has piled up in the waste chute, which may cause a tool head collision.",
    "0C008009": "Build plate localization marker was not found.",
    "0C00800A": "The detected build plate is not the same as in G-code.",
    "0C00C003": "Possible defects were detected in the first layer.",
    "0C00C004": "Possible spaghetti failure was detected.",
    "0C00C006": "Purged filament may have piled up in the waste chute.",
    "1000C001": "High bed temperature may lead to filament clogging in the nozzle. You may open the chamber door.",
    "1000C002": "Printing CF material with stainless steel may cause nozzle damage.",
    "1000C003": "Enabling traditional timelapse might lead to defects. Please enable it as needed?",
    "1001C001": "Timelapse is not supported because Spiral vase is enabled in slicing presets.",
    "1001C002": "Timelapse is not supported because Print sequence is set to 'By object'.",
    "12004001": "Filament is still loaded from the AMS when it has been disabled. Please unload AMS filament, load from spool holder, and restart print job.",
    "12008001": "Cutting the filament failed. Please check to see if the cutter is stuck. Refer to the Assistant for solutions.",
    "12008002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "12008003": "Failed to pull out the filament from the extruder. Please check whether the extruder is clogged or whether the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12008004": "Failed to pull back the filament from the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12008005": "Failed to feed the filament. Please load the filament, then click the 'Retry' button.",
    "12008006": "Unable to feed filament into the extruder. This could be due to entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "12008007": "Failed to extrude the filament. This might be caused by clogged extruder or stuck filament. Refer to the Assistant for solutions.",
    "12008010": "Filament or spool may be stuck.",
    "12008011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "12008012": "Failed to get AMS mapping table. Please click the 'Retry' button to continue.",
    "12008013": "Timeout while purging old filament. Please check if the filament is stuck or the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "12008014": "The filament location in the toolhead was not found. Refer to the Assistant for solutions.",
    "12008015": "Failed to pull out the filament from the toolhead. Please check if the filament is stuck, or the filament is broken inside the extruder or PTFE tube.",
    "12008016": "The extruder is not extruding normally. Refer to the Assistant for troubleshooting. There may be defects in this layer, you may resume if the defects are acceptable.",
    "12014001": "Filament is still loaded from the AMS when it has been disabled. Please unload AMS filament, load from spool holder, and restart print job.",
    "12018001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "12018002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "12018003": "Failed to pull out the filament from the extruder. Please check whether the extruder is clogged or whether the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12018004": "Failed to pull back the filament from the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12018005": "Failed to feed the filament. Please load the filament and then click the 'Retry' button.",
    "12018006": "Failed to feed the filament into the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12018007": "Failed to extrude the filament. The extruder may be clogged or the filament may be stuck; please refer to HMS. After troubleshooting, click 'Retry' button.",
    "12018010": "Please check if the spool or filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12018011": "AMS filament has run out. Please insert a new filament into the same AMS slot.",
    "12018012": "Failed to get AMS mapping table; please click the 'Retry' button to continue.",
    "12018013": "Timeout while purging old filament. Please check if the filament is stuck or the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "12018014": "Failed to check the filament location in the tool head; please refer to the HMS. After troubleshooting, click the 'Retry' button.",
    "12018015": "Failed to pull back the filament from the toolhead. Please check if the filament is stuck or the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12018016": "The extruder is not extruding normally; please refer to the HMS. After trouble shooting. If the defects are acceptable, please click 'Retry' button.",
    "12024001": "Filament is still loaded from the AMS when it has been disabled. Please unload AMS filament, load from spool holder, and restart print job.",
    "12028001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "12028002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "12028003": "Failed to pull out the filament from the extruder. Please check whether the extruder is clogged or whether the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12028004": "Failed to pull back the filament from the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12028005": "Failed to feed the filament. Please load the filament, then click the 'Retry' button.",
    "12028006": "Failed to feed the filament into the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12028007": "Failed to extrude the filament. The extruder may be clogged or the filament may be stuck; please refer to HMS. After troubleshooting, click 'Retry' button.",
    "12028010": "Please check if the spool or filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12028011": "AMS filament has run out. Please insert a new filament into the same AMS slot.",
    "12028012": "Failed to get AMS mapping table; please click the 'Retry' button to continue.",
    "12028013": "Timeout while purging old filament. Please check if the filament is stuck or the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "12028014": "Failed to check the filament location in the tool head; please refer to the HMS. After troubleshooting, click the 'Retry' button.",
    "12028015": "Failed to pull back the filament from the toolhead. Please check if the filament is stuck or is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12028016": "The extruder is not extruding normally; please refer to the HMS. After trouble shooting. If the defects are acceptable, please click 'Retry' button.",
    "12034001": "Filament is still loaded from the AMS when it has been disabled. Please unload AMS filament, load from spool holder, and restart print job.",
    "12038001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "12038002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "12038003": "Failed to pull out the filament from the extruder. Please check whether the extruder is clogged or whether the filament is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12038004": "Failed to pull back the filament from the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12038005": "Failed to feed the filament. Please load the filament, then click the 'Retry' button.",
    "12038006": "Failed to feed the filament into the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12038007": "Failed to extrude the filament. The extruder may be clogged or the filament may be stuck; please refer to HMS. After troubleshooting, click 'Retry' button.",
    "12038010": "Please check if the spool or filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12038011": "AMS filament has run out. Please insert a new filament into the same AMS slot.",
    "12038012": "Failed to get AMS mapping table; please click the 'Retry' button to continue.",
    "12038013": "Timeout while purging old filament. Please check if the filament is stuck or the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "12038014": "Failed to check the filament location in the tool head; please refer to the HMS. After troubleshooting, click the 'Retry' button.",
    "12038015": "Failed to pull back the filament from the toolhead. Please check if the filament is stuck or is broken inside the extruder. After troubleshooting, click the 'Retry' button.",
    "12038016": "The extruder is not extruding normally; please refer to the HMS. After trouble shooting. If the defects are acceptable, please click 'Retry' button.",
    "12FF4001": "Filament is still loaded from the AMS when it has been disabled. Please unload AMS filament, load from spool holder, and restart print job.",
    "12FF8001": "Failed to cut the filament. Please check the cutter. After troubleshooting, click the 'Retry' button.",
    "12FF8002": "The cutter is stuck. Please pull out the cutter handle and click the 'Retry' button.",
    "12FF8003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder or PTFE Tube. (Connect PTFE tube if you are about to use AMS)",
    "12FF8004": "Failed to pull back the filament from the toolhead. Please check whether the filament is stuck. After troubleshooting, click the 'Retry' button.",
    "12FF8005": "Failed to feed the filament. Please load the filament, then click the 'Retry' button.",
    "12FF8006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "12FF8007": "Check nozzle. Click 'Done' if filament was extruded, otherwise push filament forward slightly and click 'Retry.'",
    "12FF8010": "Please check if the filament or the spool is stuck.",
    "12FF8011": "AMS filament has run out. Please insert a new filament into the same AMS slot.",
    "12FF8012": "Failed to get AMS mapping table; please click the 'Retry' button to continue.",
    "12FF8013": "Timeout while purging old filament. Please check if the filament is stuck or the extruder clogged. After troubleshooting, click the 'Retry' button.",
    "12FFC003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder or PTFE Tube. (Connect PTFE tube if you are about to use AMS)",
    "12FFC006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
}
