name: Bug report
description: Create a report to help us improve
title: "[Bug] <Replace this part>"
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: How can we replicate this?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device are you using?
      options:
        - X1C
        - P1P
    validations:
      required: true
  - type: input
    id: firmware
    attributes:
      label: Firmware Version
      description: What version of the firmware are you using? (Please get this from
        the printer, not Home Assistant)
  - type: input
    id: haversion
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant?
    validations:
      required: true
  - type: input
    id: componentversion
    attributes:
      label: Component Version
      description: What version of this component?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Extracts
      description: Any log information?
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: Anything else we should know?
