name: Bug report
description: Create a report to help us improve
title: "[Bug] <Replace this part>"
labels:
  - bug
body:
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      placeholder: 2024.11.1
    validations:
      required: true
  - type: input
    id: habl-version
    attributes:
      label: Bambu Lab Integration Version
      placeholder: v2.0.33
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: How can we replicate this?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device are you using?
      options:
        - A1
        - A1 Mini
        - H2D
        - P1P
        - P1S
        - X1
        - X1C
        - X1E
        - AMS
        - AMS 2 Pro
        - AMS HT
        - AMS Lite
    validations:
      required: true
  - type: textarea
    id: diagnostic
    attributes:
      label: Diagnostic Output
      placeholder: Paste content here or drag and drop log files to the other information field.
      description: |
        Add your Diagnostics file download. To get this, go to the Home Assistant Bambu Lab Integration, and click Download Diagnostics
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Log Extracts
      placeholder: Paste content here or drag and drop log files to the other information field.
      render: shell
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: Anything else we should know?
