name: Feature Request
description: Request a feature
title: "[Feature] <Replace this part>"
labels:
  - "feature request"
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device is this for?
      options:
        - A1
        - A1 Mini
        - H2C
        - H2D
        - H2S
        - P1P
        - P1S
        - P2S
        - X1
        - X1C
        - X1E
        - AMS
        - AMS 2 Pro
        - AMS HT
        - AMS Lite
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: Anything else we should know?
