name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install test dependencies
        run: pip install -r tests/requirements.txt

      - name: Run pybambu unit tests
        run: python -m pytest tests/pybambu -v
